include:
 - board: seeeduino_xiao_ble
   shield: roBa_L nice_epaper
   snippet: studio-rpc-usb-uart
# - board: seeeduino_xiao_ble
#   shield: roBa_R
# - board: seeeduino_xiao_ble
#   shield: settings_reset
