manifest:
  remotes:
    - name: waryong94
      url-base: https://github.com/waryong94
  projects:
    - name: zmk
      remote: waryong94
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: waryong94
      revision: main
    - name: zmk-nice-oled
      remote: waryong94
      revision: main
   - name: zmk-input-behavior-listener
      remote: waryong94
      revision: main
  self:
    path: config
